### ISSUE TITLE
Хотелки по запросу «Список игр»

### ISSUE THREAD

**Issue by tuner7777** [maxkol/vtb#5]
Несколько хотелок и вопросов по запросу «[Список игр](https://org.infobasket.su/Comp/GetCalendar/?comps=37492&from=01.03.2022&to=31.03.2022&max=100» и «[Данные о LIVE играх»](https://org.infobasket.su/Widget/GetOnlineStatus/?games=153807):
1. Добавить свойство о данных посещаемости
2. Для live данных о играх добавить информацию о командных фолах для каждой из команд, счётчик должен сбрасываться при смене четверти

**Comment by maxkol** [comment]
1. Добавил GameAttendance, сегодня-завтра выложу
2. GetCalendar фолов не будет - это точно лишнее. Думаю как в GeOnlineStatus добавить

**Comment by tuner7777** [comment]
Я тоже думаю надо добавить в метод GeOnlineStatus, эти данные актуальны именно для live игры
